### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by wooorm** [Casburggraaf/cssttr#1]
<img width="337" alt="screen shot 2018-02-12 at 21 17 38" src="https://user-images.githubusercontent.com/944406/36117528-368161bc-103a-11e8-8904-5ae83e7b8aa7.png">

🤔

**Comment by Casburggraaf** [comment]
Closed with -> https://github.com/Casburggraaf/cssttr/commit/561eca5d026138ceee831feb6cbfa8712df6ac50
