### ISSUE TITLE
Useless min-width

### ISSUE THREAD

**Issue by wooorm** [Casburggraaf/cssttr#6]
https://github.com/Casburggraaf/cssttr/blob/a00eac480255480b0323f642f468781c6912a63e/app/static/css/style.css#L17

I think the body is always 100% width... 🤔

**Comment by Casburggraaf** [comment]
Closed with -> https://github.com/Casburggraaf/cssttr/commit/561eca5d026138ceee831feb6cbfa8712df6ac50
