### ISSUE TITLE
max-width on body

### ISSUE THREAD

**Issue by wooorm** [Casburggraaf/cssttr#7]
https://github.com/Casburggraaf/cssttr/blob/a00eac480255480b0323f642f468781c6912a63e/app/static/css/style.css#L28

Why use percentages? I think, if you’re doing percentages, you should use them with width:

**Comment by wooorm** [comment]
whoops, commented to early. I also wanted to say that your login is very wide. Maybe you should use something like:

```css
body > * {
  max-width: 34em;
  width: 90%;
}
```

That, way, the elements are `90%` of the width of the screen, but at most `34em`!

**Comment by Casburggraaf** [comment]
Closed with -> https://github.com/Casburggraaf/cssttr/commit/561eca5d026138ceee831feb6cbfa8712df6ac50
